name: semgrep-sast-scan-and-import-to-defectdojo
on:
  push
jobs:
  semgrep-sast-scan:
    name: semgrep sast scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: semgrep scan
        run: |
          mkdir -p semgrep/results
          semgrep --config auto --include='*SqlInjection*.java' --json --output=semgrep/results/semgrep.json
      - name: import scan results into defectdojo
        run: |
          curl -X POST "${{ secrets.defectdojo_url }}/api/v2/import-scan/" \
            -H "accept: application/json" \
            -H "Content-Type: multipart/form-data" \
            -H "Authorization: Token ${{ secrets.defectdojo_token }}" \
            -F "scan_date=$(date +'%Y-%m-%d')" \
            -F "scan_type=Semgrep JSON Report" \
            -F "file=@semgrep/results/semgrep.json;type=application/json" \
            -F "tags=github_actions,ci" \
            -F "product_name=webgoat_demo" \
            -F "source_code_management_uri=${{ github.server_url }}/${{ github.repository }}" \
            -F "branch_tag=${{ github.ref }}" \
            -F "commit_hash=${{ github.sha }}" \
            -F "close_old_findings=true"
